### ISSUE TITLE
Fr Pack not working

### ISSUE THREAD

**Issue by Ademking** [jycr/sonar-l10n-fr#26]
This pack is not working 
Version: sonarqube 8.5.1.38104

![image](https://user-images.githubusercontent.com/12462188/101122446-d3ff1700-35f2-11eb-80db-db2a6b0eb378.png)

**Comment by ktibi** [comment]
+1

**Comment by jycr** [comment]
Current working branch: [feature/upgrade-for-sonarqube-9](https://github.com/jycr/sonar-l10n-fr/tree/feature/upgrade-for-sonarqube-9) has a lot of changes. I think this issue will be fix.
