### ISSUE TITLE
Date of last analysis not displayed correctly in projects list

### ISSUE THREAD

**Issue by sgaspari** [jycr/sonar-l10n-fr#27]
Hi,

I'm facing a minor display issue with latest release 1.15.1 and SonarQube 8.9.8 LTS: the date of last analysis is always displayed as "_{0}_" string on projects list page.
![image](https://user-images.githubusercontent.com/38781470/167445307-58d01dbc-a433-40b1-97f9-ca7a2cea46c0.png)

However the tooltip when mouse pointer is over this field displays the right date which is correctly stored.
The root cause seems coming from the `projects.last_analysis_on_x` property:
- _core.properties_ bundled in SonarQube install package: `projects.last_analysis_on_x=Last analysis: {date}`
- _core_fr.properties_ (French language pack plugin): `projects.last_analysis_on_x=Derni\u00E8re analyse : {0}`

**Comment by jycr** [comment]
Current working branch: [feature/upgrade-for-sonarqube-9](https://github.com/jycr/sonar-l10n-fr/tree/feature/upgrade-for-sonarqube-9) has a lot of changes. I think this issue will be fix.

**Comment by jycr** [comment]
fixed by: d94423f49c443a1d20ee57b9e38938335a5d235a
